function [A,B] = botStateJacFcn(x,tau,pvstate)
%botStateJacFcn
%    [A,B] = botStateJacFcn(IN1,IN2,PVSTATE1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    06-Nov-2024 15:01:36

tau1 = tau(1,:);
tau2 = tau(2,:);
x3 = x(3,:);
t2 = cos(x3);
t3 = sin(x3);
t6 = 1.0./pvstate;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t6.*(t2.*tau1+t3.*tau2)],[3,3]);
if nargout > 1
    t4 = t2.^2;
    t5 = t3.^2;
    t7 = t4+t5;
    B = reshape([t7,0.0,-t3.*t6,0.0,t7,t2.*t6],[3,2]);
end
end
